Redo install GNOME Display Manager (GDM) configs
This was done because, through testing, I found that the keyfiles
inserted into the /etc/dconf/db/gdm.d directory did not have any effect
on the GDM in the Debian 13/Trixie operating system (OS). According to
Debian's documentation, the /etc/gdm3/greeter.dconf-defaults file should
be used for customizing GDM's appearance. Hence, that is the file I
based this solution around. Their documentation states this here:
https://wiki.debian.org/GDM#Customizing_the_GDM_appearance.

The choice to use the pcre2grep executable over a grep command like
'grep --null-data --perl-regexp' is because pcre2grep doesn't require
having to work around null bytes in its output when doing multiline
matching. Even when I tried working around this, I noticed things
wouldn't work if more than one group of key-value pairs was present.

The variable name schema_group represents a group of key-value pairs
within a keyfile. So, for example, the '[org/gnome/desktop/interface]'
group contains the clock-format key-value pair. An additional resource
on the keyfile format can be read here:
https://gnome.pages.gitlab.gnome.org/glibmm/classGlib_1_1KeyFile.html#details.

diff --git a/scripts/install-gdm-configs b/scripts/install-gdm-configs
--- a/scripts/install-gdm-configs
+++ b/scripts/install-gdm-configs
@@ -7,28 +7,59 @@ set -eo pipefail
 # constants
 PROGNAME="$(basename "$0")"
 readonly PROGNAME
-readonly ROOT_UID=0
 
-if [ "$(id --user)" != "${ROOT_UID}" ]; then
-    printf "%s: %s\n" "${PROGNAME}" "you must run this as root" >&2
+if ! [ "$(command -v pcre2grep)" ]; then
+    printf '%s: %s\n' "${PROGNAME}" "pcre2grep cannot be found in the PATH!" >&2
     exit 1
 fi
 
-install --mode 644 "./src/gdm/profile" "/etc/dconf/profile/gdm"
-install \
+sudo install \
     -D \
     --mode 644 \
-    --target-directory "/etc/dconf/db/gdm.d" \
-    "./src/gdm/00-desktop-configs"
+    "./src/gdm/greeter.dconf-defaults" \
+    "/etc/gdm3/greeter.dconf-defaults" \
 
-if [ -r "./src/gdm/00-desktop-configs.local" ]; then
-    install \
+if [ -r "./src/gdm/greeter.dconf-defaults.local" ]; then
+    schema_group=""
+    temp_file_path="$(mktemp)"
+    while read -r line; do
+        if ! [ "${line}" ]; then
+            printf '%s\n' "${line}" >> "${temp_file_path}"
+        elif [ "${line:0:1}" = "[" ]; then
+            escaped_line="$(\
+                sed \
+                    's/\[/\\[/; s/\]/\\]/g; s|\/|\\/|g' \
+                    <<< "${line}" \
+            )"
+
+            if grep \
+                --quiet \
+                "${escaped_line}" \
+                "./src/gdm/greeter.dconf-defaults.local" \
+            ; then
+                schema_group="$(\
+                    pcre2grep \
+                        --multiline \
+                        "^${escaped_line}(\n\S+)+" \
+                        "./src/gdm/greeter.dconf-defaults.local" \
+                )"
+            fi
+
+            printf '%s\n' "${line}" >> "${temp_file_path}"
+        else
+            if local_line="$(grep "${line/=*/=}" <<< "${schema_group}")"; then
+                printf '%s\n' "${local_line}" >> "${temp_file_path}"
+            else
+                printf '%s\n' "${line}" >> "${temp_file_path}"
+            fi
+        fi
+    done < "./src/gdm/greeter.dconf-defaults"
+
+    sudo install \
         -D \
         --mode 644 \
-        --target-directory "/etc/dconf/db/gdm.d" \
-        "./src/gdm/00-desktop-configs.local"
+        "${temp_file_path}" \
+        "/etc/gdm3/greeter.dconf-defaults"
 fi
-
-dconf update
 
 exit 0
