Enable the ShellCheck check prefer-double-quotes
This was done because of a personal preference to use double-quoted
strings over single-quoted strings and always forgetting what characters
Bash has a special interpretation of. This check is implemented in my
fork of ShellCheck, and currently I do not intend to try merging this
upstream. Hence, my decision to also maintain a fork of its pre-commit
Git repository as well.

diff --git a/scripts/install-firefox-configs b/scripts/install-firefox-configs
--- a/scripts/install-firefox-configs
+++ b/scripts/install-firefox-configs
@@ -9,12 +9,12 @@ PROGNAME="$(basename "$0")"
 readonly PROGNAME
 
 if ! [ "$(command -v curl)" ]; then
-    printf '%s: %s\n' "${PROGNAME}" "curl cannot be found in the PATH!" >&2
+    printf "%s: %s\n" "${PROGNAME}" "curl cannot be found in the PATH!" >&2
     exit 1
 fi
 
 if ! [ "$(command -v yq)" ]; then
-    printf '%s: %s\n' "${PROGNAME}" "yq cannot be found in the PATH!" >&2
+    printf "%s: %s\n" "${PROGNAME}" "yq cannot be found in the PATH!" >&2
     exit 1
 fi
 
diff --git a/scripts/install-gdm-configs b/scripts/install-gdm-configs
--- a/scripts/install-gdm-configs
+++ b/scripts/install-gdm-configs
@@ -9,7 +9,7 @@ PROGNAME="$(basename "$0")"
 readonly PROGNAME
 
 if ! [ "$(command -v pcre2grep)" ]; then
-    printf '%s: %s\n' "${PROGNAME}" "pcre2grep cannot be found in the PATH!" >&2
+    printf "%s: %s\n" "${PROGNAME}" "pcre2grep cannot be found in the PATH!" >&2
     exit 1
 fi
 
@@ -24,7 +24,7 @@ if [ -r "./src/gdm/greeter.dconf-defaults.local" ]; then
     temp_file_path="$(mktemp)"
     while read -r line; do
         if ! [ "${line}" ]; then
-            printf '%s\n' "${line}" >> "${temp_file_path}"
+            printf "%s\n" "${line}" >> "${temp_file_path}"
         elif [ "${line:0:1}" = "[" ]; then
             escaped_line="$(\
                 sed \
@@ -45,12 +45,12 @@ if [ -r "./src/gdm/greeter.dconf-defaults.local" ]; then
                 )"
             fi
 
-            printf '%s\n' "${line}" >> "${temp_file_path}"
+            printf "%s\n" "${line}" >> "${temp_file_path}"
         else
             if local_line="$(grep "${line/=*/=}" <<< "${schema_group}")"; then
-                printf '%s\n' "${local_line}" >> "${temp_file_path}"
+                printf "%s\n" "${local_line}" >> "${temp_file_path}"
             else
-                printf '%s\n' "${line}" >> "${temp_file_path}"
+                printf "%s\n" "${line}" >> "${temp_file_path}"
             fi
         fi
     done < "./src/gdm/greeter.dconf-defaults"
diff --git a/scripts/install-plymouth b/scripts/install-plymouth
--- a/scripts/install-plymouth
+++ b/scripts/install-plymouth
@@ -32,7 +32,7 @@ install_plymouth_pkg() {
             "https://github.com/cavcrosby/plymouth/releases/download/debian/24.004.60-5.1.1/${pkg}_24.004.60-5.1.1_amd64.deb" \
     )"; then
         printf \
-            '%s: %s: %s\n' \
+            "%s: %s: %s\n" \
             "${PROGNAME}" \
             "couldn't fetch ${pkg} package" \
             "${res}" \
@@ -51,7 +51,7 @@ install_plymouth_pkg() {
 }
 
 if ! [ "$(command -v curl)" ]; then
-    printf '%s: %s\n' "${PROGNAME}" "curl cannot be found in the PATH!" >&2
+    printf "%s: %s\n" "${PROGNAME}" "curl cannot be found in the PATH!" >&2
     exit 1
 fi
 
diff --git a/scripts/print-dupkeybinds b/scripts/print-dupkeybinds
--- a/scripts/print-dupkeybinds
+++ b/scripts/print-dupkeybinds
@@ -17,7 +17,7 @@ SCHEMAS=(
 )
 
 if ! [ "$(command -v gsettings)" ]; then
-    printf '%s: %s\n' "${PROGNAME}" "gsettings cannot be found in the PATH!" >&2
+    printf "%s: %s\n" "${PROGNAME}" "gsettings cannot be found in the PATH!" >&2
     exit 1
 fi
 
@@ -36,7 +36,7 @@ for schema in "${SCHEMAS[@]}"; do
             && [ \
                 "${value}" \
                 != \
-                '@as []' \
+                "@as []" \
             ] \
         ; then
             # parses keybindings to loop over by mangling the following:
@@ -44,11 +44,11 @@ for schema in "${SCHEMAS[@]}"; do
             #   - ', '
             #   - ']
             for keybinding in $(\
-                printf '%s' "${value}" \
-                | sed 's/\['\''//; s/'\'', '\''/ /g; s/'\''\]//'\
+                printf "%s" "${value}" \
+                | sed "s/\['//; s/', '/ /g; s/'\]//" \
             ); do
                 printf \
-                    '%s %s %s\n' \
+                    "%s %s %s\n" \
                     "${schema}" \
                     "${key}" \
                     "['${keybinding}']" \
diff --git a/scripts/set-nautilus-icons b/scripts/set-nautilus-icons
--- a/scripts/set-nautilus-icons
+++ b/scripts/set-nautilus-icons
@@ -16,7 +16,7 @@ set_location_icon() {
         "metadata::custom-icon-name" \
         "${icon_name}" 2> "/dev/null"; then
             printf \
-                '%s: %s\n' \
+                "%s: %s\n" \
                 "${PROGNAME}" \
                 "${location_path} no such file or directory" \
                 >&2
@@ -24,14 +24,14 @@ set_location_icon() {
 }
 
 if ! [ "$(command -v gsettings)" ]; then
-    printf '%s: %s\n' "${PROGNAME}" "gsettings cannot be found in the PATH!" >&2
+    printf "%s: %s\n" "${PROGNAME}" "gsettings cannot be found in the PATH!" >&2
     exit 1
 fi
 
 icon_theme="$(gsettings get "org.gnome.desktop.interface" "icon-theme" | tr --delete "'")"
-if ! printf '%s' "${icon_theme}" | grep --quiet "Papirus"; then
+if ! printf "%s" "${icon_theme}" | grep --quiet "Papirus"; then
     printf \
-        '%s: %s\n' \
+        "%s: %s\n" \
         "${PROGNAME}" \
         "expected a Papirus icon theme to be set" \
         >&2
